version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: kitabi-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: kitabi
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - kitabi-network

  # Redis Cache (Optional)
  redis:
    image: redis:7.2-alpine
    container_name: kitabi-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - kitabi-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kitabi-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/kitabi?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - kitabi-network

  # Frontend Web App
  frontend:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    container_name: kitabi-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - kitabi-network

  # AI Services (Python)
  ai-services:
    build:
      context: ./ai-services
      dockerfile: Dockerfile
    container_name: kitabi-ai
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      FLASK_ENV: production
      API_URL: http://backend:5000/api
    depends_on:
      - backend
    networks:
      - kitabi-network

volumes:
  mongodb_data:
  redis_data:

networks:
  kitabi-network:
    driver: bridge
