[build]
  builder = "nixpacks"
  buildCommand = "npm install"

[deploy]
  startCommand = "npm start"
  restartPolicyType = "ON_FAILURE"
  healthcheckPath = "/health"
  healthcheckTimeout = 300
  sleepApplication = false

[env]
  NODE_ENV = "production"
