[build]
  builder = "nixpacks"
  buildCommand = "npm install"

[deploy]
  startCommand = "npm start"
  restartPolicyType = "always"
  healthcheckPath = "/health"
  healthcheckTimeout = 100

[env]
  NODE_ENV = "production"
